app:
  version: '@project.version@'
  version-file-location: "/var/www/clansite/kloepiebot/version.json"
  kloepiebot:
    installer-path: "/var/kloepiebot/KloepieBotInstaller.msi"
    installer-filename: "KloepieBotInstaller.msi"
  storage:
    location:
      champion-cards: "/var/www/clansite/images/champions/"
  upload:
    roster-path: "/var/www/clansite/upload/roster-sync/"
  backup:
    enabled: true
    location: "/var/www/clansite/backups/"

discord:
  bot-token: ${DISCORD_BOT_TOKEN}
  clan-server-id: "1062302225701015552"
  kloep-id: "270588526267990017"
  roles:
    clan-leader-id: "1298810713309057067"
    deputy-id: "1298810856804454461"
    siege-coordinator-id: "1428676592791453778"
    t1-id: "1298811143699169350"
    t2-id: "1374237716149174453"
spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/kloepiebot}
      database: kloepiebot
      auto-index-creation: true
  session:
    store-type: mongodb
    timeout-seconds: 31536000
  security:
    oauth2:
      client:
        registration:
          discord:
            client-id: "1449091367102840907"
            client-secret: ${DISCORD_CLIENT_SECRET}
            client-name: Discord
            provider: discord
            scope: identify
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: client_secret_post
        provider:
          discord:
            authorization-uri: https://discord.com/oauth2/authorize
            token-uri: https://discord.com/api/oauth2/token
            user-info-uri: https://discord.com/api/users/@me
            user-name-attribute: id
  application:
    name: Website for KloepieBot
server:
  forward-headers-strategy: native
  servlet:
    session:
      timeout: 31536000
  port: 8080
  error:
    whitelabel:
      enabled: false
    path: /error
logging:
  level:
    root: INFO
    com.rsl.clansite: INFO
  file:
    name: ${catalina.base:-.}/logs/application-logging/rsl-clansite.log
management:
  endpoints:
    web:
      exposure:
        include: "*"