app:
  storage:
    location:
      champion-cards: "C:/Development/images-rsl-clansite/champion-cards"
  upload:
    roster-path: "C:/Development/images-rsl-clansite/upload/roster-sync/"
  backup:
    enabled: true
    location: "C:/Development/images-rsl-clansite/backups/"
discord:
  clan-server-id: "728792086438084608"
  roles:
    clan-leader-id: "1460335321962119219"
    deputy-id: "1460335365570171024"
    siege-coordinator-id: "1460335391981699235"
    t1-id: "1460335417726468209"
    t2-id: "1460335437833965743"
spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/test-database-rsl}
      database: test-database-rsl
  security:
    oauth2:
      client:
        registration:
          discord:
            client-id: "1460257098439852084"
logging:
  file:
    name: "C:/Development/rsl-clansite.log"